// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/_middleware.ts";
import * as $2 from "./routes/api/list.ts";
import * as $3 from "./routes/api/listen.ts";
import * as $4 from "./routes/api/send.ts";
import * as $5 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/_middleware.ts": $1,
    "./routes/api/list.ts": $2,
    "./routes/api/listen.ts": $3,
    "./routes/api/send.ts": $4,
    "./routes/index.tsx": $5,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
